name: Build Snapshot
on: [push]

env:
  release_tag: snapshot

jobs:
  build:
    strategy:
      matrix:
        operating-system: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout Tiles Downloader
        uses: actions/checkout@v4
        
      - name: Setup Lazarus
        uses: gcarreno/setup-lazarus@v3
        with:
          lazarus-version: "dist"
          with-cache: false
          
      - name: Download BGRABitmapPack
      - if: ${{ matrix.operating-system == 'windows-latest' }}
        run: Invoke-WebRequest -Uri https://packages.lazarus-ide.org/BGRABitmap.zip -OutFile BGRABitmap.zip
      - if: ${{ matrix.operating-system == 'ubuntu-latest' }} 
        run: wget https://packages.lazarus-ide.org/BGRABitmap.zip

      - name: Unzip BGRABitmapPack
      - if: ${{ matrix.operating-system == 'windows-latest' }}
        run: Expand-Archive -Path BGRABitmap.zip -DestinationPath . -Force
      - if: ${{ matrix.operating-system == 'ubuntu-latest' }} 
        run: unzip BGRABitmap.zip

      - name: Build BGRABitmapPack
        run: lazbuild BGRABitmap/bgrabitmap/bgrabitmappack.lpk
        
      - name: Build Tiles Downloader
        run: lazbuild -B --bm="Release" src/tilesdownloader.lpi
