name: Build Snapshot
on: [push]

env:
  release_tag: snapshot

jobs:
  build:
    strategy:
      matrix:
        operating-system: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout Tiles Downloader
        uses: actions/checkout@v4
        
      - name: Setup Lazarus
        uses: gcarreno/setup-lazarus@v3
        with:
          lazarus-version: "dist"
          with-cache: false
          
      - name: Download BGRABitmapPack
        run: |
          if (${{ matrix.operating-system }} -eq 'windows-latest') {
            Invoke-WebRequest -Uri https://packages.lazarus-ide.org/BGRABitmap.zip -OutFile BGRABitmap.zip
          } else {
            wget https://packages.lazarus-ide.org/BGRABitmap.zip
          }

      - name: Unzip BGRABitmapPack
        run: |
          if (${{ matrix.operating-system }} -eq 'windows-latest') {
            Expand-Archive -Path BGRABitmap.zip -DestinationPath . -Force
          } else {
            unzip BGRABitmap.zip
          }

      - name: Build BGRABitmapPack
        run: lazbuild BGRABitmap/bgrabitmap/bgrabitmappack.lpk
        
      - name: Build Tiles Downloader
        run: lazbuild -B --bm="Release" src/tilesdownloader.lpi
